CREATE TABLE employee_performance (
  perf_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   NUMBER NOT NULL,
  evaluator_id  NUMBER NOT NULL,
  perf_date     DATE DEFAULT SYSDATE,
  rating        NUMBER(1) CHECK (rating BETWEEN 0 AND 5),
  CONSTRAINT fk_perf_employee FOREIGN KEY (employee_id)
    REFERENCES employees(employee_id),
  CONSTRAINT fk_perf_evaluator FOREIGN KEY (evaluator_id)
    REFERENCES employees(employee_id)
);

