
-- ================================================
-- Create Table: employee_evaluations
-- ================================================

CREATE TABLE employee_evaluations (
    evaluation_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       NUMBER NOT NULL,
    evaluator_id      NUMBER NOT NULL,
    evaluation_date   DATE NOT NULL DEFAULT SYSDATE,
    evaluation_score  NUMBER(1) NOT NULL CHECK (evaluation_score BETWEEN 0 AND 5),
    comments          VARCHAR2(500),

    CONSTRAINT fk_eval_employee FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id),

    CONSTRAINT fk_eval_evaluator FOREIGN KEY (evaluator_id)
        REFERENCES employees(employee_id),

    CONSTRAINT chk_eval_not_self CHECK (employee_id <> evaluator_id)
);

-- Indexes for performance
CREATE INDEX idx_eval_employee ON employee_evaluations(employee_id);
CREATE INDEX idx_eval_date ON employee_evaluations(evaluation_date);
