
-- ================================================
-- HR Schema - Initial Data Model
-- Excludes employee_evaluations table
-- Generated on 2025-05-05
-- ================================================

-- Drop tables if they exist (for dev/reset purposes)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE salary_history CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE departments CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE jobs CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Table: departments
CREATE TABLE departments (
    department_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name   VARCHAR2(100) NOT NULL,
    location          VARCHAR2(100)
);

-- Table: jobs
CREATE TABLE jobs (
    job_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title   VARCHAR2(100) NOT NULL,
    min_salary  NUMBER(10,2),
    max_salary  NUMBER(10,2)
);

-- Table: employees
CREATE TABLE employees (
    employee_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR2(50) NOT NULL,
    last_name             VARCHAR2(50) NOT NULL,
    email                 VARCHAR2(100) NOT NULL UNIQUE,
    hire_date             DATE NOT NULL,
    salary                NUMBER(10,2) NOT NULL,
    last_salary_review    DATE,
    fire_date             DATE,
    department_id         NUMBER,
    manager_id            NUMBER,
    job_id                NUMBER,
    
    CONSTRAINT fk_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id),
    CONSTRAINT fk_manager
        FOREIGN KEY (manager_id) REFERENCES employees(employee_id),
    CONSTRAINT fk_job
        FOREIGN KEY (job_id) REFERENCES jobs(job_id),
    
    CONSTRAINT chk_salary_positive CHECK (salary > 0),
    CONSTRAINT chk_dates CHECK (fire_date IS NULL OR fire_date > hire_date)
);

-- Indexes
CREATE INDEX idx_emp_dept ON employees(department_id);
CREATE INDEX idx_emp_manager ON employees(manager_id);
CREATE INDEX idx_emp_job ON employees(job_id);

-- Table: salary_history
CREATE TABLE salary_history (
    history_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    NUMBER NOT NULL,
    old_salary     NUMBER(10,2),
    new_salary     NUMBER(10,2),
    change_date    DATE DEFAULT SYSDATE,
    reason         VARCHAR2(200),
    
    CONSTRAINT fk_salary_emp FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id)
);
